spring:
  profiles:
    include: routers, jwt

  redis:
    host: 127.0.0.1
    port: 6379

logging:
  level:
    com.dosth: debug
    org:
      springframework:
        cloud:
          gateway: debug